DROP DATABASE IF EXISTS DBSISTEMACOVID;

CREATE DATABASE DBSISTEMACOVID;

USE DBSISTEMACOVID;

CREATE TABLE PESSOA (
	IDPESSOA INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    SEXO CHAR(1) NOT NULL,
    CPF CHAR(11) NOT NULL,
    TIPO TINYINT NOT NULL,
    PRIMARY KEY (IDPESSOA)
);

CREATE TABLE VACINA (
	IDVACINA INT NOT NULL AUTO_INCREMENT,
    IDPESQUISADOR INT NOT NULL,
    PAIS_ORIGEM VARCHAR(255) NOT NULL,
    ESTAGIO_PESQUISA INT NOT NULL,
    DATA_INICIO_PESQUISA DATE NOT NULL,
    PRIMARY KEY(IDVACINA, IDPESQUISADOR),
    CONSTRAINT FK_VACINA_PESQUISADOR FOREIGN KEY (IDPESQUISADOR) REFERENCES PESSOA (IDPESSOA)
);

CREATE TABLE NOTA (
	IDNOTA INT NOT NULL AUTO_INCREMENT,
    IDVACINA INT NOT NULL,
    IDPESSOA INT NOT NULL,
    VALOR DECIMAL(10,4) NOT NULL,
    PRIMARY KEY(IDNOTA),
    CONSTRAINT FK_NOTA_VACINA FOREIGN KEY (IDVACINA) REFERENCES VACINA(IDVACINA),
    CONSTRAINT FK_NOTA_PESSOA FOREIGN KEY (IDPESSOA) REFERENCES PESSOA(IDPESSOA)
);

DELIMITER $$

# VERIFICAR SE A PESSOA RELACIONADA NA FK DA VACINA É DO TIPO PESQUISADOR (TIPO = 0)
CREATE TRIGGER TR_VACINA_BI BEFORE INSERT ON VACINA FOR EACH ROW
BEGIN
	DECLARE TIPO INT;
    
    SELECT TIPO
    INTO TIPO
    FROM PESSOA
    WHERE IDPESSOA = NEW.IDPESQUISADOR;
    
    IF (TIPO != 0) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'A pessoa definida como pesquisador responsável, não é um pesquisador!';
    END IF;
END $$

DELIMITER ;