USE DBSISTEMACOVID;

SET SQL_SAFE_UPDATES = 0;

SELECT * FROM TIPO;
SELECT * FROM INSTITUICAO;
select * from PESSOA;
SELECT * FROM PESSOA NATURAL JOIN TIPO;
SELECT V.*, CONCAT(P.NOME,' ',P.SOBRENOME) AS 'PESQUISADOR' FROM VACINA V
	INNER JOIN PESSOA P ON V.IDPESQUISADOR = P.IDPESSOA;
SELECT N.IDNOTA, V.NOME, P.NOME, N.VALOR 
	FROM NOTA N NATURAL JOIN VACINA V 
	INNER JOIN PESSOA P ON P.IDPESSOA = N.IDPESSOA
    ORDER BY N.IDNOTA;
SELECT * FROM NOTA;

DELETE FROM INSTITUICAO;
ALTER TABLE INSTITUICAO AUTO_INCREMENT = 1;

DELETE FROM PESSOA;
ALTER TABLE PESSOA AUTO_INCREMENT = 1;
